--- # PROMPT
- hosts: apacheweb
  user: test
  sudo: yes
  connection: ssh
  gather_facts: no
  vars: 
   playbook_version: 0.01b
  vars_prompt: 
   - name: pkgtoinstall
     prompt: Install which package?
     default: telnet
     private: no 
  tasks:
   - name: Install the indicated package - {{ pkgtoinstall }}
     yum: pkg={{ pkgtoinstall }} state=latest
