--- # WHEN
- hosts: aptserver
  user: test
  sudo: yes
  connection: ssh
  vars:
   playbook_type: condtionalexample
  vars_files:
   - conf/copyright.yml
   - conf/webdefaults.yml
  tasks:
   - name: Install apache based on distro - DEBIAN/UBUNTU
     command: apt -y install apache2
     when: ansible_os_family == 'Debian'
   - name: Install apache based on distro
     command: yum -y install httpd - RHEL/CENTOS
     when: ansible_os_family == 'RedHat' 
